package io.UnityConstants;

/**
 * This class stores the constants we may need for Unity for convenient access.
 * 
 * @author kschenk
 * 
 */
public class UnityConstants {
	/**
	 * All files generated by ScriptEase should have this prefix.
	 */
	public static final String SCRIPTEASE_FILE_PREFIX = "se_";

	/**
	 * The prefix for all tags. This is followed immediately by the type number.
	 */
	public static final String UNITY_TAG = "tag:unity3d.com,2011:";
}
